apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ecommerce
  labels:
    app: ecommerce-backend
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"

  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-svc:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"

  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"

  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQLDialect"

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when_authorized"

  LOGGING_LEVEL_ROOT: "WARN"
  LOGGING_LEVEL_COM_ECOMMERCE: "INFO"